name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      [
        'packages/artifacts/*.json',
        'packages/artifacts/*.jsonc',
        'packages/artifacts/**/*.ts',
      ]

jobs:
  check:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - uses: pnpm/actions-setup@v4
      with:
        run_install: false

    - shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      with:
        path: ${{env.STORE_PATH}}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store

    - run: pnpm i

    - name: Check formatting, linting and import sorting
      run: pnpm --filter @zk-kit/artifacts check
